apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: foreverhome
    component: backend
spec:
  selector:
    app: foreverhome
    component: backend
  ports:
    - port: 80
      targetPort: 5158
      protocol: TCP
  type: ClusterIP
