apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-blue
  namespace: doe25-gg
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
      version: blue
  template:
    metadata:
      labels:
        app: web
        version: blue
    spec:
      containers:
        - name: web
          image: hashicorp/http-echo:1.0.0
          args:
            - -text=blue
            - -listen=:8080
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-green
  namespace: doe25-gg
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
      version: green
  template:
    metadata:
      labels:
        app: web
        version: green
    spec:
      containers:
        - name: web
          image: hashicorp/http-echo:1.0.0
          args:
            - -text=green
            - -listen=:8080
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: doe25-gg
spec:
  type: ClusterIP
  selector:
    app: web
    version: blue
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: doe25-gg
spec:
  containers:
    - name: client
      image: busybox:1.36
      command: ["sh", "-c", "sleep infinity"]
